services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: python -m gunicorn app:app

